
CREATE TABLE  CRUD_EMP(EMPLOYEE_ID NUMBER NOT NULL PRIMARY KEY ,CODE VARCHAR(50),
                          NAME VARCHAR(50), PASSWORD VARCHAR(50), EMAIL VARCHAR(50),MOBILE_NUMBER NUMBER(10),
    ADDRESS VARCHAR(50));
    
    
    
    INSERT INTO CRUD_EMP(CODE,NAME,PASSWORD ,EMAIL,MOBILE_NUMBER,ADDRESS) VALUES 
    
    ('EM456','raja','raja@1234','raja@gmail.com',9988998899,'hyd');